### ISSUE TITLE
Add Logs Command

### ISSUE THREAD

**Issue by jaredhaight** [FactionC2/CLI#5]
**Is your feature request related to a problem? Please describe.**
Right now to view logs I need to run `cd /opt/faction/installer` and then `docker-compose -p faction logs <optional container name>`. This should be simplified.

**Describe the solution you'd like**
I should just be able to run `faction logs <optional_container_name>`, it should take an optional `-f` param to follow logs.

This would be implemented under `/processing/docker/logs.py` with a function like

```py
def get_logs(container_name=None, follow=false):
    # build and run command to follow logs
```

The the corresponding command would be added under `/commands/log.py` and that command registered in `/setup.py`

**Additional context**
Because the way to build and run commands is demonstrated several times in the project, this should be a pretty easy issue for someone new to the project or python.

**Comment by rmikehodges** [comment]
Submitted a PR for this which falls in line with your guidance above (naming conventions, location, etc.)

**Comment by jaredhaight** [comment]
Thanks Mike!
